name: deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: checkout merge commit
      uses: actions/checkout@v5

    - name: set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: install dependencies
      run: |
        conda install -y python=3.13
        conda env update --file environment.yml --name base
        echo $CONDA/bin >> $GITHUB_PATH

    - name: build the book
      run: |
        cd manuscript;make html

    - name: deploy book's HTML to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: manuscript/_build/html

    - name: build the book pdf
      run: |
        sudo apt install -y --fix-missing latexmk;cd manuscript;make latexpdf

    - name: deploy book's PDF to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: manuscript/_build/latex/tools4scicomp.pdf
